tasks:
  - name: terraform
    # env:
    #     TF_LOG=DEBUG
    #     TF_LOG_CORE=DEBUG
    #     TF_LOG_PROVIDER=DEBUG
    before: |
      cd $PROJECT_ROOT
      source ./bin/build_tf_provider.sh
      source ./bin/set_tf_alias.sh
      source ./bin/install-terraform.sh
      source ./bin/generate-tf-credentials.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/set_tf_alias.sh
      source ./bin/install-aws-cli.sh
  - name: http-server
    before: |
      cd $PROJECT_ROOT
      npm install -g http-server
  - name: sinatra
    before: | 
      cd $PROJECT_ROOT
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb 
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - golang.go
    
    
